"""Generate offline Dart holiday data from pinned source facts.
Run from repository root: python tool/generate_iranian_holidays.py
No network access. See docs/IRANIAN_HOLIDAYS_VERIFICATION.md.
"""
import datetime
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
source = root / 'third_party/iranian_holidays'
events = json.loads((source / 'events.json').read_text(encoding='utf-8'))
starts = json.loads((source / 'month_starts.json').read_text(encoding='utf-8'))
lines = ["// Generated by tool/generate_iranian_holidays.py; do not hand-edit.",
         "// Source facts and provenance: third_party/iranian_holidays/README.md.",
         "const iranianFixedHolidays = <(int, int, String)>["]
for event in events:
    if event['calendar'] == 'Persian':
        lines.append(f"  ({event['month']}, {event['day']}, {json.dumps(event['title'], ensure_ascii=False)}),")
lines += ['];', '', 'const iranianVariableHolidays = <(int, int, int, String)>[']
for current, following in zip(starts, starts[1:]):
    year, month = current['hijri']
    start = datetime.date.fromisoformat(current['gregorian'])
    end = datetime.date.fromisoformat(following['gregorian'])
    if following['hijri'] != ([year, month + 1] if month < 12 else [year + 1, 1]):
        raise ValueError('Nonconsecutive lunar months')
    length = (end - start).days
    if length not in (29, 30):
        raise ValueError('Invalid lunar month length')
    for event in events:
        if event['calendar'] != 'Hijri' or event['month'] != month:
            continue
        day = length if event['rule'] == 'end of month' else event['day']
        date = start + datetime.timedelta(days=day - 1)
        lines.append(f"  ({date.year}, {date.month}, {date.day}, {json.dumps(event['title'], ensure_ascii=False)}),")
# Exact published 1405 dates: never extrapolate a lunar conversion.
annual = json.loads((source / 'time_ir_1405.json').read_text(encoding='utf-8'))
assert annual['year'] == 1405
assert [m['month'] for m in annual['months']] == list(range(1, 13))
assert sum(m['day_count'] for m in annual['months']) == 365
for month in annual['months']:
    rows = [r for r in annual['holidays'] if r['jalali_month'] == month['month']]
    assert sorted({r['jalali_day'] for r in rows}) == month['official_days']
for row in annual['holidays']:
    assert row['jalali_year'] == 1405 and row['base'] in (0, 2)
    if row['base'] == 0:
        assert any(e['calendar'] == 'Persian' and
                   (e['month'], e['day']) == (row['jalali_month'], row['jalali_day'])
                   for e in events)
        continue
    matches = [e for e in events if e['calendar'] == 'Hijri' and
               e['month'] == row['hijri_month'] and
               (e['rule'] == 'end of month' or e['day'] == row['hijri_day'])]
    assert matches, f"Unrecognized official occasion: {row}"
    date = datetime.date(row['gregorian_year'], row['gregorian_month'], row['gregorian_day'])
    assert datetime.date(2026, 3, 21) <= date < datetime.date(2027, 3, 21)
    for event in matches:
        lines.append(f"  ({date.year}, {date.month}, {date.day}, {json.dumps(event['title'], ensure_ascii=False)}),")
lines += ['];', '']
(root / 'lib/features/calendar/domain/iranian_holiday_data.dart').write_text('\n'.join(lines), encoding='utf-8')
