"""Generate offline Dart holiday data from pinned CC0 source snapshots.
Run from repository root: python tool/generate_iranian_holidays.py
No network access. See docs/IRANIAN_HOLIDAYS_VERIFICATION.md.
"""
import datetime
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
source = root / 'third_party/iranian_holidays'
events = json.loads((source / 'events.json').read_text(encoding='utf-8'))
starts = json.loads((source / 'month_starts.json').read_text(encoding='utf-8'))
lines = ["// Generated by tool/generate_iranian_holidays.py; do not hand-edit.",
         "// CC0 source snapshots and provenance: third_party/iranian_holidays/README.md.",
         "const iranianFixedHolidays = <(int, int, String)>["]
for event in events:
    if event['calendar'] == 'Persian':
        lines.append(f"  ({event['month']}, {event['day']}, {json.dumps(event['title'], ensure_ascii=False)}),")
lines += ['];', '', 'const iranianVariableHolidays = <(int, int, int, String)>[']
for current, following in zip(starts, starts[1:]):
    year, month = current['hijri']
    start = datetime.date.fromisoformat(current['gregorian'])
    end = datetime.date.fromisoformat(following['gregorian'])
    if following['hijri'] != ([year, month + 1] if month < 12 else [year + 1, 1]):
        raise ValueError('Nonconsecutive lunar months')
    length = (end - start).days
    if length not in (29, 30):
        raise ValueError('Invalid lunar month length')
    for event in events:
        if event['calendar'] != 'Hijri' or event['month'] != month:
            continue
        day = length if event['rule'] == 'end of month' else event['day']
        date = start + datetime.timedelta(days=day - 1)
        lines.append(f"  ({date.year}, {date.month}, {date.day}, {json.dumps(event['title'], ensure_ascii=False)}),")
lines += ['];', '']
(root / 'lib/features/calendar/domain/iranian_holiday_data.dart').write_text('\n'.join(lines), encoding='utf-8')
