import 'dart:convert';
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:planact/core/database/app_database.dart';
import 'package:planact/core/errors/app_error.dart';
import 'package:planact/features/backup/data/sqlite_backup_snapshot.dart';
import 'package:planact/features/backup/data/sqlite_backup_storage.dart';
import 'package:sqlite3/sqlite3.dart' as sqlite;

// Fresh schemas were generated by the committed AppDatabase + generated Drift
// bindings at each named revision. chain fixtures were generated by opening the
// same file sequentially with revisions 0a1bea4, 95c4003, 4e13275, 3ae1198,
// 02bc301, 09f9c44, 444b2d3, c42a3e1, b64416d, a14dade, 58bc343, b9dd2f0,
// 184f8e7, 2edbc33, fb69495. The -v16 files retain actual historical migration
// output. fresh-v16 uses the committed fb69495-v16 declarations as an explicit
// v16 input (not a newly inferred schema). The -v17 files are actual current
// migration output, not schemas with constraints selectively removed.
const fixtures = [
  'a14dade',
  '58bc343',
  'b9dd2f0',
  '184f8e7',
  '2edbc33',
  'fb69495',
  'chain-v10',
  'chain-v11',
  'chain-v12',
  'chain-v13',
  'chain-v14',
  'chain-v15',
  'fresh-v16',
];

Future<void> createHistorical(File file, String fixture) async {
  final data = jsonDecode(
    await File('test/fixtures/backup_schema/$fixture.json').readAsString(),
  ) as Map<String, dynamic>;
  final raw = sqlite.sqlite3.open(file.path);
  try {
    final declarations = (data['sql'] as List).cast<String>();
    for (final sql in [
      ...declarations.where((sql) => sql.startsWith('CREATE TABLE')),
      ...declarations.where((sql) => !sql.startsWith('CREATE TABLE')),
    ]) {
      raw.execute(sql);
    }
    raw.execute('PRAGMA user_version = ${data['version']}');
    raw.execute(
      "INSERT INTO schema_metadata(key,value) VALUES ('schema_version', ?)",
      ['${data['version']}'],
    );
    raw.execute(
      "INSERT INTO commitments(id,title,created_at,status,tags) VALUES ('legacy','historical',0,0,'آموزش')",
    );
    if (data['version'] == 16) {
      raw.execute(
        "INSERT INTO tags(id,label,normalized_label,created_at) VALUES ('legacy-tag','آموزش','آموزش',0)",
      );
      raw.execute(
        "INSERT INTO commitment_tags(commitment_id,tag_id) VALUES ('legacy','legacy-tag')",
      );
    }
    raw.execute(
      "INSERT INTO financial_accounts(id,name,currency,type,status) VALUES ('account','wallet','IRR',0,0)",
    );
    raw.execute(
      "INSERT INTO account_entries(id,account_id,type,minor_units,currency,occurred_at) VALUES ('entry','account',0,1200,'IRR',0)",
    );
  } finally {
    raw.close();
  }
}

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late Directory directory;
  late List<String> expected;
  late SqliteBackupStorage storage;

  setUp(() async {
    directory = await Directory.systemTemp.createTemp('backup-schema-');
    final fresh = File('${directory.path}/fresh.sqlite');
    final database = AppDatabase.forTesting(NativeDatabase(fresh));
    await database.readMetadata('schema_version');
    await database.close();
    final raw = sqlite.sqlite3.open(fresh.path);
    expected = SqliteBackupStorage.schema(raw);
    raw.close();
    storage = SqliteBackupStorage(
      live: fresh,
      schemaVersion: 17,
      expectedSchema: expected,
      snapshot: fresh.readAsBytes,
      closeLive: () async {},
    );
  });

  tearDown(() async => directory.delete(recursive: true));

  test('fresh v17 still validates', () async {
    await storage.validatePayload(await storage.live.readAsBytes());
  });

  for (final fixture in fixtures) {
    test(
      '$fixture real migration exports and validates after restart',
      () async {
        final file = File('${directory.path}/legacy.sqlite');
        await createHistorical(file, fixture);
        var database = AppDatabase.forTesting(NativeDatabase(file));
        expect(await database.readMetadata('schema_version'), '17');
        await database.close();
        final raw = sqlite.sqlite3.open(file.path);
        try {
          final reference = (jsonDecode(
            await File('test/fixtures/backup_schema/$fixture-v17.json')
                .readAsString(),
          ) as List).cast<String>();
          expect(SqliteBackupStorage.schema(raw), reference);
          expect(SqliteBackupStorage.schema(raw), isNot(expected));
          expect(
            raw.select('SELECT title FROM commitments').single['title'],
            'historical',
          );
          expect(
            raw
                .select('SELECT minor_units FROM account_entries')
                .single['minor_units'],
            1200,
          );
        } finally {
          raw.close();
        }
        database = AppDatabase.forTesting(NativeDatabase(file));
        try {
          final bytes = await sqliteBackupSnapshot(
            database: database,
            target: File('${directory.path}/export.sqlite'),
            redact: true,
          );
          await storage.validatePayload(bytes);
          await storage.writeSafetySnapshot(bytes);
          await storage.writeTemporary(bytes);
          final exported = sqlite.sqlite3.open(storage.temporary.path);
          try {
            expect(
              exported.select('SELECT label FROM tags').single['label'],
              'آموزش',
            );
            expect(
              exported
                  .select('SELECT minor_units FROM account_entries')
                  .single['minor_units'],
              1200,
            );
          } finally {
            exported.close();
          }
        } finally {
          await database.close();
        }
      },
    );
  }

  final mutations = <String, void Function(sqlite.Database)>{
    'missing table': (db) => db.execute('DROP TABLE actuals'),
    'missing review history guard': (db) =>
        db.execute('DROP TRIGGER relationship_reviews_no_update'),
    'missing review revision index': (db) =>
        db.execute('DROP INDEX relationship_reviews_transaction_revision'),
    'missing review FK': (db) => rewrite(
      db,
      'relationship_reviews',
      (sql) => sql.replaceAll(' REFERENCES account_entries (id)', ''),
    ),
    'missing index': (db) => db.execute('DROP INDEX tags_normalized_label'),
    'changed unique index': (db) {
      db.execute('DROP INDEX reminder_instances_logical_identity');
      db.execute(
        'CREATE INDEX reminder_instances_logical_identity ON reminder_instances(rule_id, occurrence_id, scheduled_at)',
      );
    },
    'changed index columns': (db) {
      db.execute('DROP INDEX tags_normalized_label');
      db.execute('CREATE INDEX tags_normalized_label ON tags(label)');
    },
    'removed check': (db) => rewrite(
      db,
      'occurrences',
      (sql) => sql.replaceAll(' CHECK ("is_manual_override" IN (0, 1))', ''),
    ),
    'weakened check': (db) => rewrite(
      db,
      'occurrences',
      (sql) => sql.replaceAll('IN (0, 1)', 'IN (0, 1, 2)'),
    ),
    'missing FK': (db) => rewrite(
      db,
      'account_entry_tags',
      (sql) => sql.replaceAll(' REFERENCES account_entries(id)', ''),
    ),
    'changed FK target': (db) => rewrite(
      db,
      'account_entry_tags',
      (sql) => sql.replaceAll(
        'REFERENCES account_entries(id)',
        'REFERENCES commitments(id)',
      ),
    ),
    'changed default': (db) => rewrite(
      db,
      'commitments',
      (sql) => sql.replaceAll('DEFAULT 1', 'DEFAULT 2'),
    ),
    'extra trigger': (db) => db.execute(
      'CREATE TRIGGER unexpected AFTER INSERT ON commitments BEGIN DELETE FROM account_entries; END',
    ),
    'extra table': (db) => db.execute('CREATE TABLE unexpected(id TEXT)'),
    'wrong metadata': (db) => db.execute(
      "UPDATE schema_metadata SET value='15' WHERE key='schema_version'",
    ),
    'wrong version': (db) => db.execute('PRAGMA user_version = 15'),
    'FK orphan': (db) => db.execute(
      "INSERT INTO commitment_tags(commitment_id,tag_id) VALUES ('missing','missing')",
    ),
    // This FK is missing in the exact approved sequential legacy declarations.
    // foreign_key_check alone cannot detect it: isolated current constraints must.
    'legacy undeclared FK orphan': (db) =>
        db.execute("UPDATE account_entries SET account_id='missing'"),
  };
  for (final entry in mutations.entries) {
    test(
      'rejects migrated ${entry.key} without mutating payload/live',
      () async {
        final file = File('${directory.path}/tampered.sqlite');
        await createHistorical(file, 'chain-v13');
        final database = AppDatabase.forTesting(NativeDatabase(file));
        await database.readMetadata('schema_version');
        await database.close();
        final raw = sqlite.sqlite3.open(file.path);
        try {
          entry.value(raw);
        } finally {
          raw.close();
        }
        final bytes = await file.readAsBytes();
        final live = await storage.live.readAsBytes();
        await expectLater(
          storage.validatePayload(bytes),
          throwsA(isA<ValidationError>()),
        );
        expect(await file.readAsBytes(), bytes);
        expect(await storage.live.readAsBytes(), live);
        expect(
          await File('${storage.live.path}.restore-validation').exists(),
          isFalse,
        );
      },
    );
  }

  test(
    'existing incomplete v15 tag-style fixture is not a backup schema',
    () async {
      final file = File('${directory.path}/incomplete.sqlite');
      final raw = sqlite.sqlite3.open(file.path);
      raw.execute(
        'CREATE TABLE schema_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL)',
      );
      raw.execute(
        'CREATE TABLE commitments (id TEXT PRIMARY KEY, title TEXT NOT NULL, created_at INTEGER NOT NULL, status INTEGER NOT NULL, tags TEXT NOT NULL DEFAULT \'\')',
      );
      raw.execute('CREATE TABLE account_entries (id TEXT PRIMARY KEY)');
      raw.execute('CREATE TABLE financial_accounts (id TEXT PRIMARY KEY)');
      raw.execute('PRAGMA user_version = 15');
      raw.close();
      final database = AppDatabase.forTesting(NativeDatabase(file));
      await database.readMetadata('schema_version');
      await database.close();
      await expectLater(
        storage.validatePayload(await file.readAsBytes()),
        throwsA(isA<ValidationError>()),
      );
    },
  );
}

// Tamper sqlite_master only in isolated test files. Reopening the payload causes
// SQLite to parse the changed declarations; assert replacement actually happened.
void rewrite(sqlite.Database db, String table, String Function(String) change) {
  final original =
      db.select('SELECT sql FROM sqlite_master WHERE name=?', [
            table,
          ]).single['sql']
          as String;
  final modified = change(original);
  expect(
    modified,
    isNot(original),
    reason: 'negative test must change declaration',
  );
  db.execute('PRAGMA writable_schema = ON');
  db.execute('UPDATE sqlite_master SET sql=? WHERE name=?', [modified, table]);
  db.execute('PRAGMA writable_schema = OFF');
}
